server:
  port: 6003
spring:
  application:
    name: inventory-service
  profiles: 
    active: qa,default
  config:
    import: optional:configserver:http://localhost:8888

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"       

