server:
  port: 6003
spring:
  application:
    name: inventory-service
  data: 
    mongodb:
        uri: mongodb://localhost:27017/inventorydb
       

eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka