server:
  port: 7000
spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      routes:
        - id: products
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**
        
        - id: order
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/order/**

        - id: inventory
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/inventory/**
        
        - id: payment
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payments/**
